version: '2'
services:
  todo-app:
    image: todo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - ORG_NEO4J_DRIVER_URI=bolt://todo-neo4j:7687
      - JHIPSTER_CACHE_REDIS_SERVER=redis://todo-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://todo-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://todo-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://todo-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  todo-neo4j:
    extends:
      file: neo4j.yml
      service: todo-neo4j
  todo-redis:
    extends:
      file: redis.yml
      service: todo-redis
  todo-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: todo-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
